# Generated by Django 5.1.15 on 2026-05-15 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('movie', 'Film'), ('series', 'Série')], default='movie', max_length=10)),
                ('year', models.PositiveIntegerField(default=2024)),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Films seulement')),
                ('maturity', models.CharField(choices=[('ALL', 'Tous publics'), ('10', '10+'), ('13', '13+'), ('16', '16+'), ('18', '18+')], default='ALL', max_length=4)),
                ('cast', models.CharField(blank=True, max_length=400)),
                ('director', models.CharField(blank=True, max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('backdrop', models.ImageField(blank=True, null=True, upload_to='backdrops/')),
                ('poster_url', models.URLField(blank=True, help_text='Fallback si pas de fichier')),
                ('backdrop_url', models.URLField(blank=True, help_text='Fallback si pas de fichier')),
                ('trailer_url', models.URLField(blank=True, help_text='YouTube embed ou MP4')),
                ('video_url', models.URLField(blank=True, help_text='MP4 source pour le lecteur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='titles', to='catalog.genre')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField(default=1)),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('video_url', models.URLField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='catalog.title')),
            ],
            options={
                'ordering': ['season', 'number'],
                'unique_together': {('title', 'season', 'number')},
            },
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_seconds', models.PositiveIntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='accounts.profile')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='catalog.title')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('profile', 'title')},
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='accounts.profile')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_watchlists', to='catalog.title')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('profile', 'title')},
            },
        ),
    ]
